// Code generated by go-bindata.
// sources:
// src/assets/.index.html.swp
// src/assets/.script.js.swp
// src/assets/bootstrap.min.css
// src/assets/bootstrap.min.js
// src/assets/index.html
// src/assets/jquery.min.js
// src/assets/script.js
// src/assets/underscore-min.js
// DO NOT EDIT!

package communication

import (
	"net/http"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// srcAssetsIndexHtmlSwp reads file data from disk. It returns an error on failure.
func srcAssetsIndexHtmlSwp() (*asset, error) {
	path := "/home/vagrant/foobar/ssh-commander/src/assets/.index.html.swp"
	name := "src/assets/.index.html.swp"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcAssetsScriptJsSwp reads file data from disk. It returns an error on failure.
func srcAssetsScriptJsSwp() (*asset, error) {
	path := "/home/vagrant/foobar/ssh-commander/src/assets/.script.js.swp"
	name := "src/assets/.script.js.swp"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcAssetsBootstrapMinCss reads file data from disk. It returns an error on failure.
func srcAssetsBootstrapMinCss() (*asset, error) {
	path := "/home/vagrant/foobar/ssh-commander/src/assets/bootstrap.min.css"
	name := "src/assets/bootstrap.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcAssetsBootstrapMinJs reads file data from disk. It returns an error on failure.
func srcAssetsBootstrapMinJs() (*asset, error) {
	path := "/home/vagrant/foobar/ssh-commander/src/assets/bootstrap.min.js"
	name := "src/assets/bootstrap.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcAssetsIndexHtml reads file data from disk. It returns an error on failure.
func srcAssetsIndexHtml() (*asset, error) {
	path := "/home/vagrant/foobar/ssh-commander/src/assets/index.html"
	name := "src/assets/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcAssetsJqueryMinJs reads file data from disk. It returns an error on failure.
func srcAssetsJqueryMinJs() (*asset, error) {
	path := "/home/vagrant/foobar/ssh-commander/src/assets/jquery.min.js"
	name := "src/assets/jquery.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcAssetsScriptJs reads file data from disk. It returns an error on failure.
func srcAssetsScriptJs() (*asset, error) {
	path := "/home/vagrant/foobar/ssh-commander/src/assets/script.js"
	name := "src/assets/script.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// srcAssetsUnderscoreMinJs reads file data from disk. It returns an error on failure.
func srcAssetsUnderscoreMinJs() (*asset, error) {
	path := "/home/vagrant/foobar/ssh-commander/src/assets/underscore-min.js"
	name := "src/assets/underscore-min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"src/assets/.index.html.swp": srcAssetsIndexHtmlSwp,
	"src/assets/.script.js.swp": srcAssetsScriptJsSwp,
	"src/assets/bootstrap.min.css": srcAssetsBootstrapMinCss,
	"src/assets/bootstrap.min.js": srcAssetsBootstrapMinJs,
	"src/assets/index.html": srcAssetsIndexHtml,
	"src/assets/jquery.min.js": srcAssetsJqueryMinJs,
	"src/assets/script.js": srcAssetsScriptJs,
	"src/assets/underscore-min.js": srcAssetsUnderscoreMinJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"src": &bintree{nil, map[string]*bintree{
		"assets": &bintree{nil, map[string]*bintree{
			".index.html.swp": &bintree{srcAssetsIndexHtmlSwp, map[string]*bintree{}},
			".script.js.swp": &bintree{srcAssetsScriptJsSwp, map[string]*bintree{}},
			"bootstrap.min.css": &bintree{srcAssetsBootstrapMinCss, map[string]*bintree{}},
			"bootstrap.min.js": &bintree{srcAssetsBootstrapMinJs, map[string]*bintree{}},
			"index.html": &bintree{srcAssetsIndexHtml, map[string]*bintree{}},
			"jquery.min.js": &bintree{srcAssetsJqueryMinJs, map[string]*bintree{}},
			"script.js": &bintree{srcAssetsScriptJs, map[string]*bintree{}},
			"underscore-min.js": &bintree{srcAssetsUnderscoreMinJs, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}


func assetFS() http.FileSystem {
	for k := range _bintree.Children {
		return http.Dir(k)
	}
	panic("unreachable")
}
